import numpy as np
import pandas as pd
import vmmp_gmm.vmmp_utils as vmmp_utils
from vmmp_gmm.h_signature import HSignature
from collections import Counter

class VMMP:
    def __init__(self, root_trns_prob, wrd_len_prob_dict=None):
        self.root = Node(HSignature(()), root_trns_prob)
        # root of tree should be the identity character
        self.node_dict = {() : self.root}
        self.alphabet = list(root_trns_prob.keys())
        self.wrd_len_prob_dict = wrd_len_prob_dict

    def add_node(self, node_sig, trns_prob, parent):
        """ Add new node to the VMMP.

        Inputs
        --------
        node : HSignature
            HSignature of the new node, signature corresponding to suffix
        parent : tuple
            tuple identifying parent suffix node, i.e. HSignature.sig
        trns_prob : dictionary
            dictionary of probabilities that this node comes before single characters
            in given alphabet. keys are characters, values are probabilities e.g. found by
            calc_transition_prob(character, node)
        """
        if node_sig.sig in self.get_all_nodes():
            return "Node already in tree"

        new_node = Node(node_sig, trns_prob, parent)
        self.node_dict[new_node.sig.sig] = new_node
        self.node_dict[parent].add_child(new_node)

        return new_node

    def get_node_obj(self, node):
        '''Returns a node object specified by user.'''
        if isinstance(node, (tuple)): 
            node_key = node
        elif isinstance(node, (HSignature)):
            node_key = node.sig
        else:
            print('input should be string or HSignature only')
        
        try:
            return self.node_dict[node_key]
        except KeyError:
            print("Node doesn't exist")
    
    def get_all_nodes(self):
        '''Returns all node objects in the vmmp instance.'''
        return list(self.node_dict.keys())

    def get_leaves(self):
        leaves = []
        def check_node_for_leaf(node):
            if not node.children:
                leaves.append(node)
                return
            else:
                for child in node.children:
                    child_node = self.get_node_obj(child)
                    check_node_for_leaf(child_node)
        check_node_for_leaf(self.root)
        return leaves

    def get_trns_prob(self, node, character):
        '''
        Inputs
        --------
        node : tuple
            tuple of HSignature identifying the node in  vmmp, i.e. HSignature.sig
        
        character : tuple
            character in alphabet being queried.

        Returns
        --------
        Returns transition probability from node to character in alphabet nodes'''
        if isinstance(node, (tuple)): 
            node_key = node
        elif isinstance(node, (HSignature)):
            node_key = node.sig
        else:
            print('inputs should be tuple or HSignature object only')

        # print('debugging trns_prob call', node_key, character)
        return self.node_dict[node_key].trns_prob[character]
    
    def get_hsig_length_prob(self, data):
        len_hist = Counter([len(x.sig) for x in data])
        data_len = len(data)
        len_prob_dict = len_hist
        len_prob_dict = {k: v / data_len for k, v in len_prob_dict.items()}
        self.wrd_len_prob_dict = len_prob_dict

    def get_hsig_prob(self, h_sig):
        '''Returns the probability of a word being generated by this VMMP.
        Product of suffixes along a path through the graph.
        '''
        if isinstance(h_sig, (HSignature)):
            sig = h_sig.sig
        if isinstance(h_sig, (tuple)):
            sig = h_sig
        prob = 1.0
        # current_sfx = self.root
        for i in range(len(sig)):
            sfx_list = vmmp_utils.get_all_suffixes(HSignature(sig[:i]))
            sfx_list = sorted(sfx_list, key= lambda x: -len(x.sig))
            for sfx in sfx_list:
                if sfx.sig in self.get_all_nodes():
                    # print('tuple or int', (h_sig.sig[i],))
                    prob *= self.get_trns_prob(sfx, (sig[i],))
                    # print(sfx, h_sig.sig[i], h_sig.sig[:i+1], prob)
                    break
        return prob
    
    def generate_hsig(self):
        ''' Generate a HSignature of desired length given transition probabilities of
        nodes in the VMMP.'''
        word = ()
        wrd_lens = list(self.wrd_len_prob_dict.keys())
        wrd_len_probs = list(self.wrd_len_prob_dict.values())
        wrd_len_roll = np.random.multinomial(1, wrd_len_probs, size=1)
        for l, r in zip(wrd_lens, wrd_len_roll[0]):
            if r == 1:
                wrd_len = l
        i = 0
        while len(word) < wrd_len:
            # print('generating word', len(word), 'out of', wrd_len, 'word is:', word)
            sfx_list = vmmp_utils.get_all_suffixes(HSignature(word[:i]))
            # print('generating word', [x.sig for x in sfx_list])
            sfx_list = sorted(sfx_list, key=lambda x: -len(x.sig))
            for sfx in sfx_list:
                sfx_sig = sfx.sig
                # print(self.get_all_nodes())
                # print('here', sfx_sig)
                if sfx_sig in self.get_all_nodes():
                    # print('here')
                    sfx_node = self.get_node_obj(sfx_sig)
                    probs = list(sfx_node.trns_prob.values())
                    roll = np.random.multinomial(1, probs, size=1)
                    for a, r in zip(self.alphabet, roll[0]):
                        if r == 1:
                            word += a
                    # word += [a for a, r in zip(alphabet, roll[0]) if r == 1][0]
                    # print(word)
                    i+=1
                    break
        return HSignature(word)

    # def get_conditional_prob_dist(self, obs_hsig):
    #     obs_hsig_len = len(obs_hsig.sig)

    #     # use sets so that we can do complement efficiently
    #     full_sigs = {
    #         sig 
    #         for wrd_len in self.wrd_len_prob_dict.keys() 
    #         for sig in vmmp_utils.get_all_strings(self.alphabet, wrd_len) 
    #     }

    #     compatible_sigs = {x for x in full_sigs if x.sig[0:obs_hsig_len] == obs_hsig.sig}

    #     # use a dictionary to minimise number of function calls
    #     hsig_probs = {
    #         sig: self.get_hsig_prob(sig)
    #         for sig in compatible_sigs
    #     }

    #     # use python sum for python lists
    #     nrml_factor = sum(
    #                 [hsig_probs[sig] * self.wrd_len_prob_dict[len(sig.sig)] for sig in compatible_sigs]
    #                 )

    #     # compute the full sig probabilities
    #     p_full_sig = {
    #         str(full_sig): hsig_probs[full_sig] * self.wrd_len_prob_dict[len(full_sig.sig)] / nrml_factor
    #         for full_sig in compatible_sigs
    #     }

    #     # update with incomaptible ones
    #     p_full_sig_incomaptible = {
    #         str(full_sig): 0.0
    #         for full_sig in full_sigs - compatible_sigs # set complement
    #     }

    #     p_full_sig.update(p_full_sig_incomaptible)

    #     return  p_full_sig
    
    # def get_conditional_prob_dist_pandas(self, obs_hsig):
    #     obs_hsig_len = len(obs_hsig.sig)

    #     # use sets so that we can do complement efficiently
    #     full_sigs = {
    #         sig
    #         for wrd_len in self.wrd_len_prob_dict.keys() 
    #         for sig in vmmp_utils.get_all_strings(self.alphabet, wrd_len) 
    #     }

    #     compatible_sigs = {x for x in full_sigs if x.sig[0:obs_hsig_len] == obs_hsig.sig}
    #     compatible_sigs_list = list(compatible_sigs)
    #     # use a dictionary to minimise number of function calls
    #     hsig_probs = {
    #         sig: self.get_hsig_prob(sig)
    #         for sig in compatible_sigs
    #     }

    #     # use python sum for python lists
    #     nrml_factor = sum(
    #                 [hsig_probs[sig] * self.wrd_len_prob_dict[len(sig.sig)] for sig in compatible_sigs]
    #                 )

    #     # compute the full sig probabilities

    #     p_full_sig = [
    #         hsig_probs[full_sig] * self.wrd_len_prob_dict[len(full_sig.sig)] / nrml_factor
    #         for full_sig in compatible_sigs_list
    #     ]

    #     incompatible_sigs = full_sigs - compatible_sigs
    #     # update with incomaptible ones
    #     p_full_sig_incomaptible = [
    #         0.0
    #         for full_sig in incompatible_sigs # set complement
    #     ]

    #     p_full_sig.extend(p_full_sig_incomaptible)
    #     compatible_sigs_list.extend(incompatible_sigs)
    #     hsigs = list(map(HSignature.as_string,compatible_sigs_list))

    #     prob_dataframe = pd.DataFrame(p_full_sig, index = hsigs, columns=['probs'])
        
    #     return  prob_dataframe

    # def get_conditional_prob_dist_pandas_sparse(self, obs_hsig):
    #     obs_hsig_len = len(obs_hsig.sig)

    #     # use sets so that we can do complement efficiently
    #     full_sigs = {
    #         sig
    #         for wrd_len in self.wrd_len_prob_dict.keys() 
    #         for sig in vmmp_utils.get_all_strings(self.alphabet, wrd_len) 
    #     }

    #     compatible_sigs = [x for x in full_sigs if x.sig[0:obs_hsig_len] == obs_hsig.sig]

    #     # use a dictionary to minimise number of function calls
    #     hsig_probs = {
    #         sig: self.get_hsig_prob(sig)
    #         for sig in compatible_sigs
    #     }

    #     # use python sum for python lists
    #     nrml_factor = sum(
    #                 [hsig_probs[sig] * self.wrd_len_prob_dict[len(sig.sig)] for sig in compatible_sigs]
    #                 )

    #     # compute the full sig probabilities
    #     p_full_sig = [
    #         hsig_probs[full_sig] * self.wrd_len_prob_dict[len(full_sig.sig)] / nrml_factor
    #         for full_sig in compatible_sigs
    #     ]

    #     historical_sigs = [s for s in vmmp_utils.get_all_prefixes(obs_hsig)]
    #     p_historical = [0.0 for sig in historical_sigs]

    #     p_full_sig.extend(p_historical)
    #     compatible_sigs.extend(historical_sigs)
        
    #     hsigs = list(map(HSignature.as_string,compatible_sigs))

    #     prob_dataframe = pd.DataFrame(p_full_sig, index = hsigs, columns=['probs'])
        
    #     return  prob_dataframe

    def get_homotopic_belief(self, obs_hsig, gmm_hsigs):
        """Computing only over the h-sigs that are considered in the GMM to speed things up"""
        if obs_hsig.sig == ():
            #if there is no homotopic information yet, initialise uniform prior
            p_normalised = [1 / len(gmm_hsigs)
                            for sig in gmm_hsigs
                            ]
        
        else:
            obs_hsig_len = len(obs_hsig.sig)

            hsig_probs = {
                sig : self.get_hsig_prob(sig) 
                if sig.sig[0:obs_hsig_len] == obs_hsig.sig 
                else 0.0
                for sig in gmm_hsigs
            }

            nrml_factor = sum(
                [prob for prob in hsig_probs.values()]
            )

            if nrml_factor > 0:
                p_normalised = [
                    prob / nrml_factor
                    for sig, prob in hsig_probs.items()
                ]
            else:
                p_normalised = [
                    0.0
                    for sig in hsig_probs.keys()
                ]

        hsigs = list(map(HSignature.as_string, gmm_hsigs))
        prob_dataframe = pd.DataFrame(p_normalised, index = hsigs, columns=['probs'])

        return prob_dataframe
    
    # def get_homotopic_belief(self, obs_hsig, gmm_hsigs):
    # # def get_conditional_prob_dist_pandas_sparse(self, obs_hsig, gmm_hsigs):
    #     """Computing only over the h-sigs that are considered in the GMM to speed things up"""
    #     obs_hsig_len = len(obs_hsig.sig)

    #     hsig_probs = {
    #         sig : self.get_hsig_prob(sig) 
    #         if sig.sig[0:obs_hsig_len] == obs_hsig.sig 
    #         else 0.0
    #         for sig in gmm_hsigs
    #     }

    #     nrml_factor = sum(
    #         [prob * self.wrd_len_prob_dict[len(sig.sig)]
    #          for sig, prob in hsig_probs.items()
    #         ]
    #     )

    #     if nrml_factor > 0:
    #         p_normalised = [
    #             prob * self.wrd_len_prob_dict[len(sig.sig)] / nrml_factor
    #             for sig, prob in hsig_probs.items()
    #         ]
    #     else:
    #         p_normalised = [
    #             0.0
    #             for sig in hsig_probs.keys()
    #         ]

    #     hsigs = list(map(HSignature.as_string, hsig_probs.keys()))
    #     prob_dataframe = pd.DataFrame(p_normalised, index = hsigs, columns=['probs'])

    #     return prob_dataframe

    # def get_homotopic_belief_floating_index(self, obs_hsig, gmm_hsigs):
    #     obs_hsig_len = len(obs_hsig.sig)
    #     compatible_sigs = [sig for sig in gmm_hsigs if sig.sig[0:obs_hsig_len] == obs_hsig.sig]
    #     if compatible_sigs:
    #         hsig_probs = {
    #                     sig: self.get_hsig_prob(sig) for sig in compatible_sigs
    #                     }
    #         nrml_factor = sum(
    #                         [hsig_probs[sig] * self.wrd_len_prob_dict[len(sig.sig)] for sig in compatible_sigs]
    #                         )
    #         p_normalised = [
    #                         hsig_probs[sig] * self.wrd_len_prob_dict[len(sig.sig)] / nrml_factor
    #                         for sig in compatible_sigs
    #                     ]
    #         incompatible_sigs = [sig for sig in gmm_hsigs if sig not in compatible_sigs]
    #         p_incompatible = [0.0 for sig in incompatible_sigs]
    #         p_normalised.extend(p_incompatible)
    #         compatible_sigs.extend(incompatible_sigs)
    #         hsigs = list(map(HSignature.as_string,compatible_sigs))
    #     else:
    #         p_normalised = [0.0 for sig in gmm_hsigs]
    #         hsigs = list(map(HSignature.as_string,gmm_hsigs))

    #     prob_dataframe = pd.DataFrame(p_normalised, index = hsigs, columns=['probs'])
        
    #     return prob_dataframe

    # def condition_probability_dist(self, prob_dist, next_hsig):
    #     next_hsig_len = len(next_hsig.sig)

    #     hsigs = [HSignature.get_hsig_from_string(sig) for sig in prob_dist.index]
    #     compatible_sigs = [sig for sig in hsigs if sig.sig[0:next_hsig_len] == next_hsig.sig]

    #     hsig_probs = {
    #         sig : 
    #         self.get_hsig_prob(sig)
    #         for sig in compatible_sigs
    #     }
        

    #     nrml_factor = sum(
    #     [hsig_probs[sig] * self.wrd_len_prob_dict[len(sig.sig)] for sig in hsig_probs.keys()]
    #     )

    # # compute the full sig probabilities
    #     probs = [
    #         hsig_probs[full_sig] * self.wrd_len_prob_dict[len(full_sig.sig)] / nrml_factor
    #         for full_sig in hsig_probs.keys()
    #     ]
        
    #     conditional_dist = pd.DataFrame(probs, index=prob_dist.index, columns=['probs'])

    #     return conditional_dist

    @classmethod
    def get_vmmp_from_data(cls, data, alphabet, epsilon, L):
        ''' Given observed strings, train a VMMP object with same probability measure.

        Inputs
        -------
        data : list (or some other iterable container)
            list/container of observed HSignatures
        epsilon : float
            occurance threshold, probability of the candidate string must be larger than
            this threshold to be added to the set
        alphabet : list (or some iterable container)
            strings of characters that all data is constructed from
        L : int
            max length of a suffix string to be included in the VMMP, i.e. depth of VMMP
        
        Returns
        --------
        gen_vmmp : VMMP object
            the trained vmmp'''
        trns_prob = vmmp_utils.get_trns_prob_dict(HSignature(()), alphabet, data)
        gen_vmmp = cls(trns_prob)
        gen_vmmp.get_hsig_length_prob(data)

        candidate_set = vmmp_utils.get_candidate_set([], HSignature(()), data, epsilon, alphabet)
        while len(candidate_set) > 0:
            # print('candidate set:', [x.sig for x in candidate_set])
            s = candidate_set.pop()
            # s_hsig = HSignature.get_hsig_from_string(s)

            s_sfx = vmmp_utils.get_suffix(s)
            
            # s_sfx_str = s_sfx.as_string()
            # print(s.sig, s_sfx.sig)
            err = vmmp_utils.err_fn(s, s_sfx, alphabet, data)
            
            if err >= epsilon:
                # print('significant')
                for sfx in vmmp_utils.get_all_suffixes(s):
                    sfx_sig = sfx.sig
                    if sfx_sig not in gen_vmmp.get_all_nodes():
                        trns_prob = vmmp_utils.get_trns_prob_dict(sfx, alphabet, data)
                        prnt = vmmp_utils.get_suffix(sfx)
                        gen_vmmp.add_node(sfx, trns_prob, prnt.sig)
                trns_prob = vmmp_utils.get_trns_prob_dict(s, alphabet, data)
                gen_vmmp.add_node(s, trns_prob, s_sfx.sig)
            if len(s.sig) < L:
                candidate_set = vmmp_utils.get_candidate_set(candidate_set, s, data, epsilon, alphabet)
        return gen_vmmp

class Node:
    def __init__(self, sfx_sig, trns_prob, parent=None):
        self.str = sfx_sig.as_string()
        self.sig = sfx_sig
        self.parent = parent
        self.trns_prob = trns_prob
        self.children = {}
    
    def add_child(self, child):
        self.children[child.sig.sig] = child
    
    def get_children(self):
        return self.children.keys()


if __name__ == '__main__':
    #creating example from power of amnesia fig 1 for testing
    # test = VMMP({'0':0.33, '1':0.33, '-1':0.33})
    # test.add_node(HSignature(('0',)), {'0':0.5, '1':0.3, '-1':0.2}, ())
    # test.add_node(HSignature(('1',)), {'0':0.5, '1':0.3, '-1':0.2}, ())
    # test.add_node(HSignature(('-1',)), {'0':0.5, '1':0.3, '-1':0.2}, ())
    # test.add_node(HSignature(('0','0',)), {'0':0.35, '1':0.25, '-1':0.4}, ('0',))
    # test.add_node(HSignature(('1', '0',)), {'0':0.2, '1':0.7, '-1':0.1}, ('0',))
    # # print(test.get_children())
    # # if 'b' in test.get_children():
    # #     print('yes')
    # foo = HSignature(('0','0','0','0','0',))
    # print(foo.sig[3])
    # print(test.get_hsig_prob(foo))
    # print(0.33*0.5*0.35*0.35*0.35)

    # for i in range(10):
    #     word = test.generate_hsig()
    #     print(word.sig, test.get_hsig_prob(word))
    
    # print('test:', test.get_trns_prob(HSignature(('0',)),HSignature(('1',))))
    from vmmp_gmm.pickle_helper import pickle_load_data
    from vmmp_gmm.gmm import unwrap_vmmp_gmm
    from vmmp_utils import get_all_prefixes
    from ipp.cost import kl_div_np
    model = pickle_load_data(folder_path='../data', file_name='five_obs_no_empty_trained_model_L_2_tro')
    gmm_dict = model['gmm_dict']
    prior_gmm, hsig_map = unwrap_vmmp_gmm(gmm_dict)
    hsigs = [HSignature.get_hsig_from_string(sig) for sig in np.unique(hsig_map)]
    gmm_hsigs = list(set(prefix for sig in hsigs for prefix in get_all_prefixes(sig) + [sig]))
    
    vmmp = model['vmmp']

    pdf = vmmp.get_homotopic_belief(HSignature((2,)), gmm_hsigs)
    pdf2 = vmmp.get_homotopic_belief(HSignature((2,3)), gmm_hsigs)
    print(1.6078393533167817e-08 * kl_div_np(pdf, pdf2))
        
    
